feat(editor-libs): extend the feature detection for CSS functions
mdn/bob pull request #1270
Opened 2023-05-03 07:59 UTC by yarusome

This PR extends the `isPropertySupported()` function to detect browsers' supports for CSS functions. Its validity can be *deduced* as below:

  1. If `property` is not supported, then `tmpElem.style[property]` is `undefined`.
  2. If `property` is supported but the value in the example is not, then `tmpElem.style[property]` is `""`.
  3. If both `property` and the value are supported, then `tmpElem.style[property]` is a non-empty string.

---

Fixes #1269.

2023-05-03 10:24 UTC, NiedziolkaMichal requested changes
This code is always going to return false, because for unstyled `div`, all CSS properties will have an empty value. Additionally, it doesn't anyhow fix #1269 as you have stated.

2023-05-03 11:42 UTC, yarusome commented
@NiedziolkaMichal I added a second paramter to actually test the property values.

2023-05-03 12:21 UTC, NiedziolkaMichal requested changes
Could you please test the change prior to requesting a review? Currently, it breaks every CSS example. You might want to check `isCodeSupported` in `css-editor-utils.js`.

2023-05-03 14:39 UTC, yarusome commented
> Could you please test the change prior to requesting a review? Currently, it breaks every CSS example. You might want to check `isCodeSupported` in `css-editor-utils.js`.

@NiedziolkaMichal I have to confess that I have no dev environment to run a decent test, sorry :pray:

This time I followed the clue to use `isCodeSupported()` for detection, and made a simplistic "test" by copying the JS definitions for `isCodeSupported()` and `isPropertyCode()` as well as the HTML [code](https://github.com/mdn/interactive-examples/blob/main/live-examples/css-examples/color/function-hsl.html) for `hsl()` into a blank page.

May I ask you a favor to run an authentic test for one last time? If not, or the test still fails, I'd close this PR immediately (and update my naïve analysis in the issue).

2023-05-03 18:55 UTC, NiedziolkaMichal commented
@yarusome Your code works very well now, thank you. I made some small refactoring, I hope you don't mind. Sometimes CSS examples contain more than a single declaration, so I renamed the function & parameter. I have also moved it to a more appropriate file. Feel free to modify it if you wish.

@wbamberg This seems to fix your [#476](https://github.com/mdn/interactive-examples/issues/476). The proposed solution is to get rid of `data-property` in HTML files of CSS examples altogether and simply check if any example box is fully supported by the browser.

2023-05-04 17:41 UTC, wbamberg commented
> @wbamberg This seems to fix your [#476](https://github.com/mdn/interactive-examples/issues/476). The proposed solution is to get rid of `data-property` in HTML files of CSS examples altogether and simply check if any example box is fully supported by the browser.

Sounds like a good plan! Thank you both for the fix+review!

2023-05-04 18:05 UTC, NiedziolkaMichal approved these changes

2023-05-04 18:05 UTC, merged

2023-05-04 18:06 UTC, NiedziolkaMichal commented
Great. Thanks again @yarusome